### PR TITLE
Prevent the use of stale gRPC client references

### PR DESCRIPTION
**Pull request by pierventre**
Sometime, we have found that UP4 commands fails in the ONOS CLI due to the following exception:

`ERROR [ShellUtil] Exception caught while executing command
java.lang.IllegalStateException: Context is cancelled (client has been shut down)
  at org.onosproject.grpc.ctl.AbstractGrpcClient.runInCancellableContext(AbstractGrpcClient.java:110) ~[?:?]
  at org.onosproject.p4runtime.ctl.client.P4RuntimeClientImpl.execRpc(P4RuntimeClientImpl.java:265) ~[?:?]
  at org.onosproject.p4runtime.ctl.client.ReadRequestImpl.submit(ReadRequestImpl.java:319) ~[?:?]
  at org.onosproject.p4runtime.ctl.client.ReadRequestImpl.submitSync(ReadRequestImpl.java:325) ~[?:?]
  at org.stratumproject.fabric.tna.behaviour.upf.FabricUpfProgrammable.readCounter(FabricUpfProgrammable.java:571)`

This can easily happen as the gRPC client reference is initialized only the first time `setupBehavior` is called on any method of `FabricUpfProgrammable`. Unless the gRPC client is really broken and not available, this PR should fix the stale reference issue. Note that the skip behavior was introduced long time ago to fix a regression #289. However, this partial revert should not have any impact on the performance since the expensive part was the compute of the hw resources.

### CODE REVIEW

**Comment by ccascone** [comment]
Most secretive PR ever... ;)

**Comment by pierventre** [comment]
> 

Will update later the description - it is a quick and dirty fix :)

**Comment by ccascone** [comment]
Doesn't look so ugly, do we want to merge this?

**Review by daniele-moro — APPROVED** [review]

**Review by ccascone — APPROVED** [review]

**Comment by daniele-moro** [comment]
> @daniele-moro are you fine to merge it after CI pass ? Or do you want to give another shot ?

I'm ok in merging this after CI pass.

**Pull request merged**
